# Generated by Django 3.2 on 2021-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionname', models.CharField(max_length=100)),
                ('sol', models.CharField(max_length=50)),
                ('wrongans1', models.CharField(max_length=50)),
                ('wrongans2', models.CharField(max_length=50)),
                ('wrongans3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.CharField(max_length=100)),
                ('question', models.ManyToManyField(to='mcq.Question')),
            ],
        ),
    ]
