# Generated by Django 3.2 on 2021-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_alter_quiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questionList',
            field=models.ManyToManyField(to='mcq.Question'),
        ),
    ]
